"""Proste zarządzanie lokalizacją tekstów interfejsu użytkownika."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Mapping


_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "pl": {
        "app.title": "CryptoAnalyzer",
        "app.description": (
            "Narzędzie do analizy dysków i obrazów dysków\n"
            "pod kątem szyfrowania oraz struktury plików"
        ),
        "button.physical": "Dysk fizyczny",
        "button.image": "Obraz dysku",
        "button.export.json": "Eksportuj JSON",
        "button.export.csv": "Eksportuj CSV",
        "checkbox.metadata": "Zbieraj metadane plików (wolniejsze)",
        "label.depth": "Głębokość skanowania:",
        "label.depth.unlimited": "Bez limitu",
        "label.workers": "Wątki:",
        "label.status.ready": "Gotowy do analizy.",
        "status.driver.unavailable": "Sterownik TSK nie jest dostępny w tym środowisku.",
        "dialog.select.physical.title": "Wybierz dysk fizyczny",
        "dialog.select.physical.prompt": "Dostępne dyski:",
        "dialog.select.physical.none": "Nie wykryto żadnych dysków fizycznych lub brak uprawnień.",
        "dialog.select.physical.no_access": "Brak dostępu do dysków fizycznych.",
        "dialog.select.image.title": "Wybierz obraz dysku",
        "dialog.select.image.filter": "Obrazy dysków (*.img *.dd *.raw *.e01 *.vhd *.vhdx)",
        "dialog.select.image.filter.all": "Wszystkie pliki (*)",
        "dialog.select.volumes.title": "Wybierz wolumeny do analizy",
        "dialog.select.volumes.description": "Zaznacz wolumeny przeznaczone do analizy:",
        "dialog.analyze.title": "Wyniki analizy",
        "dialog.analyze.cancelled": "Analiza anulowana przez użytkownika.",
        "dialog.analyze.no_volumes": "Nie wykryto żadnych wolumenów do analizy.",
        "dialog.analyze.no_selection": "Nie wybrano wolumenów do analizy.",
        "dialog.analyze.no_sources": "Sterownik nie zwrócił żadnych źródeł do analizy.",
        "dialog.analyze.error": "Analiza zakończyła się błędem:",
        "dialog.analyze.error_report_saved": "Szczegóły błędu zapisano do: {path}",
        "dialog.report.no_results": "Najpierw uruchom analizę źródła danych.",
        "dialog.report.error": "Nie udało się zapisać raportu:",
        "dialog.report.saved": "Raport zapisano w:",
        "dialog.report.title": "Zapisz raport",
        "dialog.report.filter.json": "Pliki JSON (*.json)",
        "dialog.report.filter.csv": "Pliki CSV (*.csv)",
        "dialog.elevation.required": "Aby uzyskać dostęp do dysków fizycznych, uruchom aplikację jako administrator.",
        "dialog.elevation.button": "Uruchom ponownie jako administrator",
        "dialog.elevation.failed": "Nie udało się uruchomić aplikacji z podniesionymi uprawnieniami.",
        "dialog.metadata.skipped": "Metadane pominięte",
        "dialog.progress.cancel": "Przerwij",
        
        "filesystem.unknown": "Nieznany",
        "filesystem.encrypted": "Szyfrowany wolumen",
        "filesystem.partially_encrypted": "Częściowo szyfrowany wolumen",
        "dialog.unknown_fs.title": "Nieznany system plików",
        "dialog.unknown_fs.message": "Wolumen {identifier} ma nieznany system plików. Pominąć go i kontynuować analizę?",
        "dialog.unknown_fs.skip": "Pomiń wolumen",
        "dialog.unknown_fs.abort": "Przerwij analizę",
        "dialog.unknown_fs.no_remaining": "Nie pozostały żadne wolumeny do analizy.",
        "dialog.unknown_fs.skipping": "Pomijam wolumen {identifier}...",
        "progress.preparing": "Przygotowanie analizy...",
        "progress.running": "Analiza w toku...",
        "progress.cancelling": "Anulowanie analizy...",
        "progress.session.init": "Inicjalizacja sesji",
        "progress.session.detected_volumes": "Wykryto {count} wolumen(y)",
        "progress.volume.preparing": "Wolumen {identifier}: przygotowanie",
        "progress.volume.encryption": "Wolumen {identifier}: analiza szyfrowania",
        "progress.volume.metadata": "Wolumen {identifier}: skanowanie metadanych",
        "progress.volume.metadata_with_percent": "Wolumen {identifier}: skanowanie metadanych ({percent}%)",
        "progress.volume.completed": "Wolumen {identifier}: analiza zakończona",
        "progress.volume.metadata_skipped": "Wolumen {identifier}: metadane pominięte ({reason})",
        "progress.analysis.completed": "Analiza zakończona",
        "progress.report.saved": "Raport został zapisany",
        "progress.metadata.detail.directory": "Katalog: {path}",
        "progress.metadata.detail.file": "Plik: {path}",
        "progress.metadata.reason.unknown_fs": "nieznany system plików",
        "progress.metadata.reason.detected": "wykryto {algorithm}",
        "status.analysis.completed": "Analiza {description} zakończona pomyślnie.",
        "status.analysis.completed.generic": "Analiza zakończona pomyślnie.",
        "status.analysis.failed": "Analiza zakończyła się błędem.",
        "status.analysis.cancelled": "Analiza anulowana.",
        "encryption.status.not_detected": "Brak",
        "encryption.status.encrypted": "Zaszyfrowany",
        "encryption.status.partially_encrypted": "Częściowo zaszyfrowany",
        "encryption.status.unknown": "Nieznany",
        "column.name": "Nazwa",
        "column.type": "Typ",
        "column.size": "Rozmiar",
        "column.encryption": "Szyfrowanie",
        "column.details": "Szczegóły",
        "tree.volume": "wolumen ({filesystem})",
        "tree.metadata_skipped": "Metadane pominięte",
        "tree.directory": "katalog",
        "tree.file": "plik",
        "language.label": "Język:",
        "language.polish": "Polski",
        "language.english": "English",
        "summary.source": "Źródło: {display_name}",
        "summary.metadata.volume.collected": "  Metadane: odczytane",
        "summary.metadata.volume.skipped": "  Metadane: pominięte",
        "summary.metadata.volume.skipped_with_reason": "  Metadane: pominięte ({reason})",
        "summary.volume": "- {identifier}: FS={filesystem}, szyfrowanie={encryption} (algorytm: {algorithm})",
        "summary.totals.volumes": "Łączna liczba wolumenów: {count}",
        "summary.totals.files": "Łączna liczba plików: {count}",
        "summary.totals.directories": "Łączna liczba katalogów: {count}",
        "summary.metadata.enabled": "Metadane plików: tak",
        "summary.metadata.disabled": "Metadane plików: nie",
        "ai.section.title": "AI",
        "ai.button.open": "Analiza AI",
        "ai.dialog.title": "Analiza AI",
        "ai.section.disabled": "AI wyłączone (ustaw CRYPTOAI_API_KEY oraz CRYPTOAI_ENDPOINT w zmiennych środowiskowych lub w pliku .env; CRYPTOAI_MODEL jest opcjonalne).",
        "ai.summary.title": "Streszczenie AI",
        "ai.suspicious.title": "Podejrzane aktywności (AI)",
        "ai.next_steps.title": "Następne kroki (AI)",
        "ai.qa.title": "Pytania i odpowiedzi (AI)",
        "ai.qa.placeholder": "Zadaj pytanie o wyniki analizy…",
        "ai.qa.ask": "Zapytaj",
        "ai.status.running": "AI: generowanie w toku…",
        "ai.status.failed": "AI: błąd podczas generowania.",
        "ai.error.invalid_output": "AI: nieprawidłowa odpowiedź.",
        "details.owner": "właściciel",
        "details.mtime": "mtime",
        "tree.info": "informacja",
        "dialog.analyze.error_report_failed": "Nie udało się zapisać raportu błędu.",
    },
    "en": {
        "app.title": "CryptoAnalyzer",
        "app.description": (
            "Disk and image analysis tool\n"
            "for encryption and file structure"
        ),
        "button.physical": "Physical Disk",
        "button.image": "Disk Image",
        "button.export.json": "Export JSON",
        "button.export.csv": "Export CSV",
        "checkbox.metadata": "Collect file metadata (slower)",
        "label.depth": "Scan depth:",
        "label.depth.unlimited": "No limit",
        "label.workers": "Workers:",
        "label.status.ready": "Ready for analysis.",
        "status.driver.unavailable": "TSK driver is not available in this environment.",
        "dialog.select.physical.title": "Select physical disk",
        "dialog.select.physical.prompt": "Available disks:",
        "dialog.select.physical.none": "No physical disks detected or insufficient permissions.",
        "dialog.select.physical.no_access": "No access to physical disks.",
        "dialog.select.image.title": "Choose disk image",
        "dialog.select.image.filter": "Disk images (*.img *.dd *.raw *.e01 *.vhd *.vhdx)",
        "dialog.select.image.filter.all": "All files (*)",
        "dialog.select.volumes.title": "Select volumes for analysis",
        "dialog.select.volumes.description": "Mark the volumes to analyze:",
        "dialog.analyze.title": "Analysis results",
        "dialog.analyze.cancelled": "Analysis cancelled by user.",
        "dialog.analyze.no_volumes": "No volumes detected for analysis.",
        "dialog.analyze.no_selection": "No volumes selected for analysis.",
        "dialog.analyze.no_sources": "Driver did not return any sources for analysis.",
        "dialog.analyze.error": "Analysis finished with an error:",
        "dialog.analyze.error_report_saved": "Error details saved to: {path}",
        "dialog.report.no_results": "Run the analysis first.",
        "dialog.report.error": "Failed to save report:",
        "dialog.report.saved": "Report saved to:",
        "dialog.report.title": "Save report",
        "dialog.report.filter.json": "JSON files (*.json)",
        "dialog.report.filter.csv": "CSV files (*.csv)",
        "dialog.elevation.required": "Administrator privileges are required to access physical disks.",
        "dialog.elevation.button": "Restart as Administrator",
        "dialog.elevation.failed": "Could not relaunch the application with elevated privileges.",
        "dialog.metadata.skipped": "Metadata skipped",
        "dialog.progress.cancel": "Cancel",
        "filesystem.unknown": "Unknown",
        "filesystem.encrypted": "Encrypted volume",
        "filesystem.partially_encrypted": "Partially encrypted volume",
        "dialog.unknown_fs.title": "Unknown filesystem",
        "dialog.unknown_fs.message": "Volume {identifier} uses an unknown filesystem. Skip it and continue?",
        "dialog.unknown_fs.skip": "Skip volume",
        "dialog.unknown_fs.abort": "Abort analysis",
        "dialog.unknown_fs.no_remaining": "No volumes left to analyze.",
        "dialog.unknown_fs.skipping": "Skipping volume {identifier}...",
        "progress.preparing": "Preparing analysis...",
        "progress.running": "Analysis in progress...",
        "progress.cancelling": "Cancelling analysis...",
        "progress.session.init": "Initializing session",
        "progress.session.detected_volumes": "Detected {count} volume(s)",
        "progress.volume.preparing": "Volume {identifier}: preparing",
        "progress.volume.encryption": "Volume {identifier}: encryption analysis",
        "progress.volume.metadata": "Volume {identifier}: metadata scan",
        "progress.volume.metadata_with_percent": "Volume {identifier}: metadata scan ({percent}%)",
        "progress.volume.completed": "Volume {identifier}: analysis complete",
        "progress.volume.metadata_skipped": "Volume {identifier}: metadata skipped ({reason})",
        "progress.analysis.completed": "Analysis completed",
        "progress.report.saved": "Report saved",
        "progress.metadata.detail.directory": "Directory: {path}",
        "progress.metadata.detail.file": "File: {path}",
        "progress.metadata.reason.unknown_fs": "unknown filesystem",
        "progress.metadata.reason.detected": "detected {algorithm}",
        "status.analysis.completed": "Analysis of {description} finished successfully.",
        "status.analysis.completed.generic": "Analysis finished successfully.",
        "status.analysis.failed": "Analysis ended with an error.",
        "status.analysis.cancelled": "Analysis cancelled.",
        "encryption.status.not_detected": "Not detected",
        "encryption.status.encrypted": "Encrypted",
        "encryption.status.partially_encrypted": "Partially encrypted",
        "encryption.status.unknown": "Unknown",
        "column.name": "Name",
        "summary.metadata.volume.collected": "  Metadata: collected",
        "summary.metadata.volume.skipped": "  Metadata: skipped",
        "summary.metadata.volume.skipped_with_reason": "  Metadata: skipped ({reason})",
        "column.type": "Type",
        "column.size": "Size",
        "column.encryption": "Encryption",
        "column.details": "Details",
        "tree.volume": "volume ({filesystem})",
        "tree.metadata_skipped": "Metadata skipped",
        "tree.directory": "directory",
        "tree.file": "file",
        "language.label": "Language:",
        "language.polish": "Polish",
        "language.english": "English",
        "summary.source": "Source: {display_name}",
        "summary.volume": "- {identifier}: FS={filesystem}, encryption={encryption} (algorithm: {algorithm})",
        "summary.totals.volumes": "Total volumes: {count}",
        "summary.totals.files": "Total files: {count}",
        "summary.totals.directories": "Total directories: {count}",
        "summary.metadata.enabled": "File metadata: yes",
        "summary.metadata.disabled": "File metadata: no",
        "ai.section.title": "AI",
        "ai.button.open": "AI analysis",
        "ai.dialog.title": "AI analysis",
        "ai.section.disabled": "AI disabled (set CRYPTOAI_API_KEY and CRYPTOAI_ENDPOINT in environment variables or in a .env file; CRYPTOAI_MODEL is optional).",
        "ai.summary.title": "AI Summary",
        "ai.suspicious.title": "Suspicious Activity (AI)",
        "ai.next_steps.title": "Next Steps (AI)",
        "ai.qa.title": "Q&A (AI)",
        "ai.qa.placeholder": "Ask a question about the analysis…",
        "ai.qa.ask": "Ask",
        "ai.status.running": "AI: generating…",
        "ai.status.failed": "AI: generation failed.",
        "ai.error.invalid_output": "AI: invalid output.",
        "details.owner": "owner",
        "details.mtime": "mtime",
        "tree.info": "info",
        "dialog.analyze.error_report_failed": "Failed to write error report.",
    },
}


@dataclass(slots=True)
class LocalizationManager:
    """Eksponuje teksty interfejsu w zależności od wybranego języka."""

    locale: str = "pl"

    def set_locale(self, locale: str) -> None:
        if locale not in _TRANSLATIONS:
            raise ValueError(f"Unsupported locale: {locale}")
        self.locale = locale

    def text(self, key: str) -> str:
        table = _TRANSLATIONS.get(self.locale, _TRANSLATIONS["pl"])
        try:
            return table[key]
        except KeyError as exc:
            raise KeyError(f"Missing translation for key '{key}' in locale '{self.locale}'") from exc

    def available_locales(self) -> Mapping[str, str]:
        return {
            "pl": _TRANSLATIONS["pl"]["language.polish"],
            "en": _TRANSLATIONS["en"]["language.english"],
        }


__all__ = ["LocalizationManager"]
